In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.width', 5000) 
pd.set_option('display.max_columns', 60)

In [3]:
###########
# Download data and perform basic cleanup
###############

In [4]:
processed_data_path  ="../data/interim/"

In [5]:
deliv = pd.read_csv("https://data.ca.gov/sites/default/files/EAR%202013-2016%20DELIVERIES%20FINAL%2006-22-2018.csv")
prod = pd.read_csv("https://data.ca.gov/sites/default/files/EAR%202013-2016%20PRODUCTION%20FINAL%2006-22-2018.csv")
# data dictionary: https://data.ca.gov/dataset/drinking-water-%E2%80%93-public-water-system-annually-reported-water-production-and-delivery-4
systems = pd.read_csv("https://data.ca.gov/sites/default/files/Public%20Potable%20Water%20Systems%20FINAL%2006-22-2018_0.csv")

In [6]:
# Remove whitespace in column names
deliv.columns = [x.rstrip().lstrip() for x in deliv.columns]
prod.columns = [x.rstrip().lstrip() for x in prod.columns]
systems.columns = [x.rstrip().lstrip() for x in systems.columns]

In [7]:
##############
# Preview data
###############

In [8]:
print(deliv.shape)
print(prod.shape)
print(systems.shape)

(78537, 22)
(212824, 21)
(7898, 31)

'\n78537, 22)\n(212824, 21)\n(7898, 31)\n'

In [9]:
systems[0:3]

  Water System No                      Water System Name Principal County Served Federal Water System Type -CODE    Federal Water System Type State Water System Type -CODE      State Water System Type Water System Status -CODE Water System Status Owner Type -CODE Owner Type Primary Water Source Type -CODE Primary Water Source Type  Residential Population  Non Transient Population  Transient Population  Total Population  Number of Service Connections Agricultural  Number of COMBINED Service Connections (CB)  Number of Commercial (CM) Service Connections  Numer of Institutional Service Conections  Number of Residential Service Connections  Total Number of Service Connections Fee Code                 Fee Code Description Date of Sanitary Survey visit (SNSV Visit Date)             CITY Treatment Plant Class-CODE Treatment Plant Class Distribution System Class-CODE      Distribution System Class
0       CA1900045  1000 TRAILS / SOLEDAD CANYON PRESERVE             LOS ANGELES                              NC      Transient Non-Community                          NC        Transient Non-Community                         A              ACTIVE                P    Private                             GW                Groundwater                     NaN                       NaN                 800.0             800.0                                         NaN                                        182.0                                            NaN                                        NaN                                        NaN                                182.0    N1     Transient-Noncommunity Water System                                      11/22/2017              NaN                        NaN                   NaN                          D1     Distribution Operator Level 1
1       CA2800014                                  11:11                    NAPA                              NC      Transient Non-Community                          NC        Transient Non-Community                         A              ACTIVE                P    Private                             GW                Groundwater                     NaN                       NaN                  25.0              25.0                                         NaN                                          1.0                                            NaN                                        NaN                                        NaN                                  1.0    N1     Transient-Noncommunity Water System                                       6/17/2015             NAPA                        NaN                   NaN                          NR                      Not Required
2       CA4000725         141 SUBURBAN ROAD WATER SUPPLY         SAN LUIS OBISPO                            NTNC  Non-Transient Non-Community                          NTNC  Non-Transient Non-Community                         A              ACTIVE                P    Private                             GW                Groundwater                     NaN                      25.0                   NaN              25.0                                         NaN                                          1.0                                            NaN                                        NaN                                        NaN                                  1.0      NaN                                  NaN                                       6/23/2014  SAN LUIS OBISPO                        NaN                   NaN                          D1     Distribution Operator Level 1

In [10]:
deliv[0:3]

       PWSID                    Water.System.Name Water.System.Classification  Year     Month      Date  Days.In.Month Delivered.Water.Units AS ORIGINALLY REPORTED Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? WATER DELIVERIES TO Single.family.Residential WATER DELIVERIES TO  Multi.family.Residential WATER DELIVERIES TO  Commercial.Institutional WATER DELIVERIES TO  Industrial WATER DELIVERIES TO  Landscape.Irrigation WATER DELIVERIES TO  Other WATER DELIVERIES TO  Agricultural WATER DELIVERIES TO  Other.PWS WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS) Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)  Population Of Service Area CALCULATED GPCD (Total delivery to residential in gallons per capita day)
0  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2015   January  1/1/2015             31                                            G                                                  G                                          NO CHANGES                                       105,995                                           NaN                                           NaN                             NaN                                       NaN                        NaN                               NaN                            NaN                                         105,995.00                                                                                                                                105,995.00                                                                                      50.0                                              68.4
1  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2015  February  2/1/2015             28                                            G                                                  G                                          NO CHANGES                                        65,156                                           NaN                                           NaN                             NaN                                       NaN                        NaN                               NaN                            NaN                                          65,156.00                                                                                                                                 65,156.00                                                                                      50.0                                              46.5
2  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2015     March  3/1/2015             31                                            G                                                  G                                          NO CHANGES                                        99,975                                           NaN                                           NaN                             NaN                                       NaN                        NaN                               NaN                            NaN                                          99,975.00                                                                                                                                 99,975.00                                                                                      50.0                                              64.5

In [11]:
prod[0:3]

         PWSID                    Water.System.Name Water.System.Classification  Year     Month      Date  Days.In.Month WATER PRODUCED Water.Units IN UNITS ORIGINALLY REPORTED WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? Finished.Water.Vol.Type.Revised WATER PRODUCED FROM GROUNDWATER WATER PRODUCED FROM SURFACE WATER FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM Non-Potable Produced Water (EXCLUDING RECYCLING) RECYCLED WATER PRODUCED TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts) TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)  Population Of Service Area CALCULATED GPCD (Total Potable Produced in gallons per capita day)
0   CA0103040   NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014   January  1/1/2014             31                                                  G                                                       G                                                NO CHANGES                               M                     171,120.00                                NaN                                                NaN                                                           NaN                                              NaN                     NaN                                        171,120.00                                                                                                       171,120.00                                                                     50.0                                             110.4
1   CA0103040   NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014  February  2/1/2014             28                                                  G                                                       G                                                NO CHANGES                               M                     154,560.00                                NaN                                                NaN                                                           NaN                                              NaN                     NaN                                        154,560.00                                                                                                       154,560.00                                                                     50.0                                             110.4
2   CA0103040   NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014     March  3/1/2014             31                                                  G                                                       G                                                NO CHANGES                               M                     171,120.00                                NaN                                                NaN                                                           NaN                                              NaN                     NaN                                        171,120.00                                                                                                       171,120.00                                                                     50.0                                             110.4

In [12]:
print("Prod columns: {}".format(prod.columns.values))
print("****")
print("Deliv columns: {}".format(deliv.columns.values))
print("*****")
print("System columns: {}".format(systems.columns.values))

Prod columns: ['PWSID' 'Water.System.Name' 'Water.System.Classification' 'Year' 'Month'
 'Date' 'Days.In.Month'
 'WATER PRODUCED Water.Units IN UNITS ORIGINALLY REPORTED'
 'WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS'
 'UNITS ADJUSTED BY OIMA?' 'Finished.Water.Vol.Type.Revised'
 'WATER PRODUCED FROM GROUNDWATER' 'WATER PRODUCED FROM SURFACE WATER'
 'FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM'
 'WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM'
 'Non-Potable Produced Water (EXCLUDING RECYCLING)'
 'RECYCLED WATER PRODUCED'
 'TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)'
 'TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)'
 'Population Of Service Area'
 'CALCULATED GPCD (Total Potable Produced in gallons per capita day)']
****
Deliv columns: ['PWSID' 'Water.System.Name' 'Water.System.Classification' 'Year' 'Month'
 'Date' 'Days.In.Month' 'Delivered.Water.Units AS ORIGINALLY REPORTED'
 'Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS'
 'UNITS ADJUSTED BY OIMA?' 'WATER DELIVERIES TO Single.family.Residential'
 'WATER DELIVERIES TO  Multi.family.Residential'
 'WATER DELIVERIES TO  Commercial.Institutional'
 'WATER DELIVERIES TO  Industrial'
 'WATER DELIVERIES TO  Landscape.Irrigation' 'WATER DELIVERIES TO  Other'
 'WATER DELIVERIES TO  Agricultural' 'WATER DELIVERIES TO  Other.PWS'
 'WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)'
 'Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)'
 'Population Of Service Area'
 'CALCULATED GPCD (Total delivery to residential in gallons per capita day)']
*****
System columns: ['Water System No' 'Water System Name' 'Principal County Served'
 'Federal Water System Type -CODE' 'Federal Water System Type'
 'State Water System Type -CODE' 'State Water System Type'
 'Water System Status -CODE' 'Water System Status' 'Owner Type -CODE'
 'Owner Type' 'Primary Water Source Type -CODE'
 'Primary Water Source Type' 'Residential Population'
 'Non Transient Population' 'Transient Population' 'Total Population'
 'Number of Service Connections Agricultural'
 'Number of COMBINED Service Connections (CB)'
 'Number of Commercial (CM) Service Connections'
 'Numer of Institutional Service Conections'
 'Number of Residential Service Connections'
 'Total Number of Service Connections' 'Fee Code' 'Fee Code Description'
 'Date of Sanitary Survey visit (SNSV Visit Date)' 'CITY'
 'Treatment Plant Class-CODE' 'Treatment Plant Class'
 'Distribution System Class-CODE' 'Distribution System Class']

In [13]:
##############
# Perform cleanup of water system ID columns
###############

In [14]:
# This column has whitespace that needs to be removed
print("Original values in prod PWSID: {}".format(prod['PWSID'].values[0:5]))
prod['PWSID'] = prod['PWSID'].apply(lambda x: x.rstrip().lstrip())

print("Original values in prod PWSID: {}".format(deliv['PWSID'].values[0:5]))
deliv['PWSID'] = deliv['PWSID'].apply(lambda x: x.rstrip().lstrip())

print("Original values in systems Water System No: {}".format(systems['Water System No'].values[0:5]))
systems['Water System No'] = systems['Water System No'].apply(lambda x: str(x).rstrip().lstrip())

Original values in prod PWSID: [' CA0103040 ' ' CA0103040 ' ' CA0103040 ' ' CA0103040 ' ' CA0103040 ']
Original values in prod PWSID: ['CA0103040' 'CA0103040' 'CA0103040' 'CA0103040' 'CA0103040']
Original values in systems Water System No: ['CA1900045' 'CA2800014' 'CA4000725' 'CA1700725' 'CA0901281']

In [15]:
###########
# Search for non-numerical units in numeric columns
###############

In [16]:
numeric_prod_col = prod.columns.values[11:-2]
numeric_deliv_col = deliv.columns.values[11:-2]

print("Names of numeric columns in prod: {}".format(numeric_prod_col))
print("***")
print("Names of numeric columns in deliv: {}".format(numeric_deliv_col))

Names of numeric columns in prod: ['WATER PRODUCED FROM GROUNDWATER' 'WATER PRODUCED FROM SURFACE WATER'
 'FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM'
 'WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM'
 'Non-Potable Produced Water (EXCLUDING RECYCLING)'
 'RECYCLED WATER PRODUCED'
 'TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)'
 'TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)']
***
Names of numeric columns in deliv: ['WATER DELIVERIES TO  Multi.family.Residential'
 'WATER DELIVERIES TO  Commercial.Institutional'
 'WATER DELIVERIES TO  Industrial'
 'WATER DELIVERIES TO  Landscape.Irrigation' 'WATER DELIVERIES TO  Other'
 'WATER DELIVERIES TO  Agricultural' 'WATER DELIVERIES TO  Other.PWS'
 'WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)'
 'Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)']

In [17]:
# how are numeric values stored?
# strings with extra whitespace; commas; decimal points
print("Sample numbers in prod numeric columns: {}".format(prod['WATER PRODUCED FROM GROUNDWATER'].values))

print("Sample numbers in deliv numeric columns: {}".format(deliv['WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)'].values))

Sample numbers in prod numeric columns: [' 171,120.00 ' ' 154,560.00 ' ' 171,120.00 ' ... ' 28.00 ' ' 16.80 '
 ' 16.30 ']
Sample numbers in deliv numeric columns: ['105,995.00' '65,156.00' '99,975.00' ... '6.00' '3.30' '2.80']

In [18]:
# convert numeric columns from string to numeric

for c in numeric_prod_col:
    print(c)
    prod[c+"_numeric"] = prod[c].apply(lambda x: pd.to_numeric(str(x).replace(",",""),errors='coerce'))

for c in numeric_deliv_col:
    print(c)
    deliv[c+"_numeric"] = deliv[c].apply(lambda x: pd.to_numeric(str(x).replace(",",""),errors='coerce'))

WATER PRODUCED FROM GROUNDWATER
WATER PRODUCED FROM SURFACE WATER
FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM
WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM
Non-Potable Produced Water (EXCLUDING RECYCLING)
RECYCLED WATER PRODUCED
TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)
TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)
WATER DELIVERIES TO  Multi.family.Residential
WATER DELIVERIES TO  Commercial.Institutional
WATER DELIVERIES TO  Industrial
WATER DELIVERIES TO  Landscape.Irrigation
WATER DELIVERIES TO  Other
WATER DELIVERIES TO  Agricultural
WATER DELIVERIES TO  Other.PWS
WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)
Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)

In [19]:
# sanity check
deliv[pd.isnull(deliv[numeric_deliv_col[6]])==False][[numeric_deliv_col[5],]+ [numeric_deliv_col[5]+"_numeric",]][0:10]

    WATER DELIVERIES TO  Agricultural  WATER DELIVERIES TO  Agricultural_numeric
381                        30,000,000                                 30000000.0
382                        87,000,000                                 87000000.0
383                       425,000,000                                425000000.0
384                       737,000,000                                737000000.0
385                       897,000,000                                897000000.0
386                       809,000,000                                809000000.0
387                       972,000,000                                972000000.0
388                       905,000,000                                905000000.0
389                       555,000,000                                555000000.0
390                       386,000,000                                386000000.0

In [20]:
# sanity check
prod[pd.isnull(prod[numeric_prod_col[6]])==False][[numeric_prod_col[6],]+ [numeric_prod_col[6]+"_numeric",]][0:10]

  TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)  TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)_numeric
0                                        171,120.00                                                                                                          171120.0
1                                        154,560.00                                                                                                          154560.0
2                                        171,120.00                                                                                                          171120.0
3                                        165,600.00                                                                                                          165600.0
4                                        171,120.00                                                                                                          171120.0
5                                        229,116.00                                                                                                          229116.0
6                                        268,306.00                                                                                                          268306.0
7                                        254,778.00                                                                                                          254778.0
8                                        166,368.00                                                                                                          166368.0
9                                        185,033.00                                                                                                          185033.0

In [21]:
############
# Prepare to convert units
#############

In [22]:
prod_meta_col = list(prod.columns.values[0:10]) + ['CALCULATED GPCD (Total Potable Produced in gallons per capita day)','Population Of Service Area']
print(prod_meta_col)

deliv_meta_col = list(deliv.columns.values[0:10]) + ['CALCULATED GPCD (Total delivery to residential in gallons per capita day)','Population Of Service Area']
print(deliv_meta_col)

['PWSID', 'Water.System.Name', 'Water.System.Classification', 'Year', 'Month', 'Date', 'Days.In.Month', 'WATER PRODUCED Water.Units IN UNITS ORIGINALLY REPORTED', 'WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS', 'UNITS ADJUSTED BY OIMA?', 'CALCULATED GPCD (Total Potable Produced in gallons per capita day)', 'Population Of Service Area']
['PWSID', 'Water.System.Name', 'Water.System.Classification', 'Year', 'Month', 'Date', 'Days.In.Month', 'Delivered.Water.Units AS ORIGINALLY REPORTED', 'Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS', 'UNITS ADJUSTED BY OIMA?', 'CALCULATED GPCD (Total delivery to residential in gallons per capita day)', 'Population Of Service Area']

In [23]:
# Identify columns with water-related numbers (not population counts)
prod_water_numeric_col = [x+"_numeric" for x in numeric_prod_col if x not in prod_meta_col]
print(prod_water_numeric_col)
print("***")
deliv_water_numeric_col = [x+"_numeric" for x in numeric_deliv_col if x not in deliv_meta_col]
print(deliv_water_numeric_col)

['WATER PRODUCED FROM GROUNDWATER_numeric', 'WATER PRODUCED FROM SURFACE WATER_numeric', 'FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM_numeric', 'WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM_numeric', 'Non-Potable Produced Water (EXCLUDING RECYCLING)_numeric', 'RECYCLED WATER PRODUCED_numeric', 'TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)_numeric', 'TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)_numeric']
***
['WATER DELIVERIES TO  Multi.family.Residential_numeric', 'WATER DELIVERIES TO  Commercial.Institutional_numeric', 'WATER DELIVERIES TO  Industrial_numeric', 'WATER DELIVERIES TO  Landscape.Irrigation_numeric', 'WATER DELIVERIES TO  Other_numeric', 'WATER DELIVERIES TO  Agricultural_numeric', 'WATER DELIVERIES TO  Other.PWS_numeric', 'WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)_numeric', 'Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)_numeric']

In [24]:
prod.to_csv("{}1_initial_eda___prod_before_unit_conversion.csv".format(processed_data_path),index=False)
deliv.to_csv("{}1_initial_eda___deliv_before_unit_conversion.csv".format(processed_data_path),index=False)

In [25]:
# Melt so we have one row per different water numeric column
prod_melt = pd.melt(prod[prod_meta_col+list(prod_water_numeric_col)], id_vars=list(prod_meta_col), value_vars=list(prod_water_numeric_col))

deliv_melt = pd.melt(deliv[deliv_meta_col+list(deliv_water_numeric_col)], id_vars=list(deliv_meta_col), value_vars=list(deliv_water_numeric_col))

In [26]:
deliv_melt[0:3]

       PWSID                    Water.System.Name Water.System.Classification  Year     Month      Date  Days.In.Month Delivered.Water.Units AS ORIGINALLY REPORTED Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? CALCULATED GPCD (Total delivery to residential in gallons per capita day)  Population Of Service Area                                           variable  value
0  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2015   January  1/1/2015             31                                            G                                                  G                                          NO CHANGES                                              68.4                                                50.0  WATER DELIVERIES TO  Multi.family.Residential_...    NaN
1  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2015  February  2/1/2015             28                                            G                                                  G                                          NO CHANGES                                              46.5                                                50.0  WATER DELIVERIES TO  Multi.family.Residential_...    NaN
2  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2015     March  3/1/2015             31                                            G                                                  G                                          NO CHANGES                                              64.5                                                50.0  WATER DELIVERIES TO  Multi.family.Residential_...    NaN

In [27]:
prod_melt[0:3]

       PWSID                    Water.System.Name Water.System.Classification  Year     Month      Date  Days.In.Month WATER PRODUCED Water.Units IN UNITS ORIGINALLY REPORTED WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? CALCULATED GPCD (Total Potable Produced in gallons per capita day)  Population Of Service Area                                 variable     value
0  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014   January  1/1/2014             31                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  171120.0
1  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014  February  2/1/2014             28                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  154560.0
2  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014     March  3/1/2014             31                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  171120.0

In [28]:
prod_melt['value'].value_counts(dropna=False).reset_index()[0:10]

     index    value
0      NaN  1028188
1   8333.0    13614
2  10000.0     2524
3   5000.0     2253
4  15000.0     1866
5  20000.0     1758
6  30000.0     1631
7  25000.0     1427
8   1000.0     1367
9   2000.0     1341

In [29]:
# Remove missing values
prod_melt = prod_melt[pd.isnull(prod_melt['value'])==False]
print(prod_melt.shape)

deliv_melt = deliv_melt[pd.isnull(deliv_melt['value'])==False]
print(deliv_melt.shape)

(674404, 14)
(299648, 14)

In [30]:
############
# Convert units
# Explore units
#AF=Acre Feet, 
#CCF=Hundred Cubic Feet, 
#MG=Million Gallons
#G=Gallons, 
#HG=Hundred Gallons
#DG=Tenth Gallons, 
#CF=Tenth Cubic Feet
#-=NO UNITS REPORTEDOR OIMA REMOVED THE UNITS
#############

In [31]:
prod_melt['WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS'].value_counts(dropna=False)

G      444778
MG     118487
AF      78239
CCF     30482
-        1152
TG        879
HG        180
DG        171
CF         36
Name: WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS, dtype: int64

In [32]:
# drop rows where the units are not recorded
prod_melt = prod_melt[prod_melt['WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS']!="-"]
print(prod_melt.shape)

deliv_melt = deliv_melt[deliv_melt['Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS']!="-"]
print(deliv_melt.shape)

(673252, 14)
(297894, 14)

In [33]:
# key = original unit
# value = multiplication factor to obtain gallons
conversionDict = {"AF": 325851.43,
                  "CF": 7.48051948,
                "CCF": 748.051948,
                  "DG": 10,
                  "G":1,
                  "HG": 100.,
                  "MG": 1000000.,
                 "TG": .1}

In [34]:
# convert units to gallons based on conversionDict
prod_melt['value_gallons'] = prod_melt[['value',
      'WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS']].apply(lambda x: conversionDict[x[1]]*x[0],axis=1)

# convert units to gallons based on conversionDict
deliv_melt['value_gallons'] = deliv_melt[['value',
      'Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS']].apply(lambda x: conversionDict[x[1]]*x[0],axis=1)

In [35]:
prod_melt[0:4]

       PWSID                    Water.System.Name Water.System.Classification  Year     Month      Date  Days.In.Month WATER PRODUCED Water.Units IN UNITS ORIGINALLY REPORTED WATER PRODUCED Water.Units REVIEWED BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? CALCULATED GPCD (Total Potable Produced in gallons per capita day)  Population Of Service Area                                 variable     value  value_gallons
0  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014   January  1/1/2014             31                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  171120.0       171120.0
1  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014  February  2/1/2014             28                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  154560.0       154560.0
2  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014     March  3/1/2014             31                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  171120.0       171120.0
3  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN.      Community Water System  2014     April  4/1/2014             30                                                  G                                                       G                                                NO CHANGES                                             110.4                                         50.0  WATER PRODUCED FROM GROUNDWATER_numeric  165600.0       165600.0

In [36]:
deliv_melt[0:4]

        PWSID           Water.System.Name             Water.System.Classification  Year     Month      Date  Days.In.Month Delivered.Water.Units AS ORIGINALLY REPORTED Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? CALCULATED GPCD (Total delivery to residential in gallons per capita day)  Population Of Service Area                                           variable    value  value_gallons
81  CA0105020  ALAMEDA COUNTY FAIRGROUNDS  Nontransient Noncommunity Water System  2016   January  1/1/2016             31                                            G                                                  G                                          NO CHANGES                                               4.6                                                82.0  WATER DELIVERIES TO  Multi.family.Residential_...  11627.0        11627.0
82  CA0105020  ALAMEDA COUNTY FAIRGROUNDS  Nontransient Noncommunity Water System  2016  February  2/1/2016             29                                            G                                                  G                                          NO CHANGES                                               3.1                                                82.0  WATER DELIVERIES TO  Multi.family.Residential_...   7468.0         7468.0
83  CA0105020  ALAMEDA COUNTY FAIRGROUNDS  Nontransient Noncommunity Water System  2016     March  3/1/2016             31                                            G                                                  G                                          NO CHANGES                                               3.6                                                82.0  WATER DELIVERIES TO  Multi.family.Residential_...   9264.0         9264.0
84  CA0105020  ALAMEDA COUNTY FAIRGROUNDS  Nontransient Noncommunity Water System  2016     April  4/1/2016             30                                            G                                                  G                                          NO CHANGES                                               4.5                                                82.0  WATER DELIVERIES TO  Multi.family.Residential_...  11066.0        11066.0

In [37]:
deliv_melt[deliv_melt['Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS']!="G"][0:3]

        PWSID              Water.System.Name Water.System.Classification  Year     Month      Date  Days.In.Month Delivered.Water.Units AS ORIGINALLY REPORTED Delivered.Water.Units.Revised BY OFFICE OF INFORMATION MANAGEMENT AND ANALYSIS UNITS ADJUSTED BY OIMA? CALCULATED GPCD (Total delivery to residential in gallons per capita day)  Population Of Service Area                                           variable     value  value_gallons
93  CA0110001  ALAMEDA COUNTY WATER DISTRICT          Large Water System  2013   January  1/1/2013             31                                          CCF                                                CCF                                          NO CHANGES                                              77.7                                            340000.0  WATER DELIVERIES TO  Multi.family.Residential_...  319647.0   2.391126e+08
94  CA0110001  ALAMEDA COUNTY WATER DISTRICT          Large Water System  2013  February  2/1/2013             28                                          CCF                                                CCF                                          NO CHANGES                                              83.9                                            340000.0  WATER DELIVERIES TO  Multi.family.Residential_...  166529.0   1.245723e+08
95  CA0110001  ALAMEDA COUNTY WATER DISTRICT          Large Water System  2013     March  3/1/2013             31                                          CCF                                                CCF                                          NO CHANGES                                              87.0                                            340000.0  WATER DELIVERIES TO  Multi.family.Residential_...  335448.0   2.509325e+08

In [ ]:
############
# Count the number of recorded values per variable
###############

In [38]:
deliv_melt['variable'].value_counts()

Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)_numeric                             77747
WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)_numeric    77747
WATER DELIVERIES TO  Commercial.Institutional_numeric                                                                                                45464
WATER DELIVERIES TO  Multi.family.Residential_numeric                                                                                                27849
WATER DELIVERIES TO  Landscape.Irrigation_numeric                                                                                                    23328
WATER DELIVERIES TO  Industrial_numeric                                                                                                              17829
WATER DELIVERIES TO  Other_numeric                                                                                                                   17686
WATER DELIVERIES TO  Agricultural_numeric                                                                                                             5332
WATER DELIVERIES TO  Other.PWS_numeric                                                                                                                4912
Name: variable, dtype: int64

In [39]:
prod_melt['variable'].value_counts()

TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)_numeric                      211980
TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)_numeric    211980
WATER PRODUCED FROM GROUNDWATER_numeric                                                                                     179179
WATER PRODUCED FROM SURFACE WATER_numeric                                                                                    28998
FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM_numeric                                               22750
WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM_numeric                                                                             7602
RECYCLED WATER PRODUCED_numeric                                                                                               6536
Non-Potable Produced Water (EXCLUDING RECYCLING)_numeric                                                                      4227
Name: variable, dtype: int64

In [40]:
###########
# Pivot
############

In [41]:
# Pivot, but do not include units columns since units are now standardized to gallons
deliv_pivot = deliv_melt.pivot_table(index=[x for x in list(deliv_meta_col) if "units" not in x.lower()], columns='variable', values='value_gallons')
deliv_pivot = deliv_pivot.reset_index()

prod_pivot = prod_melt.pivot_table(index=[x for x in list(prod_meta_col) if "units" not in x.lower()], columns='variable', values='value_gallons')
prod_pivot = prod_pivot.reset_index()

In [42]:
prod_pivot.columns = [x.replace("_numeric","") for x in prod_pivot.columns.values]
deliv_pivot.columns = [x.replace("_numeric","") for x in deliv_pivot.columns.values]

In [43]:
print(prod_pivot.shape)
prod_pivot[0:3]

(202102, 17)

       PWSID                   Water.System.Name Water.System.Classification  Year     Month       Date  Days.In.Month CALCULATED GPCD (Total Potable Produced in gallons per capita day)  Population Of Service Area  FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM  Non-Potable Produced Water (EXCLUDING RECYCLING)  RECYCLED WATER PRODUCED  TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)  TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)  WATER PRODUCED FROM GROUNDWATER  WATER PRODUCED FROM SURFACE WATER  WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM
0  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN      Community Water System  2016     April   4/1/2016             30                                              85.1                                         50.0                                                NaN                                                                    NaN                      NaN                                           127710.0                                                                                        127710.0                                                                                        127710.0                                NaN                                        NaN
1  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN      Community Water System  2016    August   8/1/2016             31                                             178.6                                         50.0                                                NaN                                                                    NaN                      NaN                                           276755.0                                                                                        276755.0                                                                                        276755.0                                NaN                                        NaN
2  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN      Community Water System  2016  December  12/1/2016             31                                             135.6                                         50.0                                                NaN                                                                    NaN                      NaN                                           210175.0                                                                                        210175.0                                                                                        210175.0                                NaN                                        NaN

In [44]:
print(deliv_pivot.shape)
deliv_pivot[0:3]

(75722, 18)

       PWSID                   Water.System.Name Water.System.Classification  Year     Month       Date  Days.In.Month CALCULATED GPCD (Total delivery to residential in gallons per capita day)  Population Of Service Area  Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)  WATER DELIVERIES TO  Agricultural  WATER DELIVERIES TO  Commercial.Institutional  WATER DELIVERIES TO  Industrial  WATER DELIVERIES TO  Landscape.Irrigation  WATER DELIVERIES TO  Multi.family.Residential  WATER DELIVERIES TO  Other.PWS  WATER DELIVERIES TO  Other  WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)
0  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN      Community Water System  2016     April   4/1/2016             30                                              85.1                                                50.0                                           127710.0                                                                                               NaN                                            NaN                              NaN                                        NaN                                            NaN                             NaN                         NaN                                           127710.0
1  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN      Community Water System  2016    August   8/1/2016             31                                             178.6                                                50.0                                           276755.0                                                                                               NaN                                            NaN                              NaN                                        NaN                                            NaN                             NaN                         NaN                                           276755.0
2  CA0103040  NORRIS CANYON PROPERTY OWNERS ASSN      Community Water System  2016  December  12/1/2016             31                                             135.6                                                50.0                                           210175.0                                                                                               NaN                                            NaN                              NaN                                        NaN                                            NaN                             NaN                         NaN                                           210175.0

In [ ]:
#############
# What is the unique key of prod_pivot?
##############

In [45]:
rowCounts = prod_pivot.groupby(['PWSID','Date']).count().reset_index()
rowCounts[rowCounts['Water.System.Name']>1][0:4]

          PWSID       Date  Water.System.Name  Water.System.Classification  Year  Month  Days.In.Month  CALCULATED GPCD (Total Potable Produced in gallons per capita day)  Population Of Service Area  FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM  Non-Potable Produced Water (EXCLUDING RECYCLING)  RECYCLED WATER PRODUCED  TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)  TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)  WATER PRODUCED FROM GROUNDWATER  WATER PRODUCED FROM SURFACE WATER  WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM
6648  CA0610002   1/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1
6652  CA0610002  10/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1
6656  CA0610002  11/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1
6660  CA0610002  12/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1

In [46]:
prod_pivot[ (prod_pivot['PWSID']=="CA3410022")
          & (prod_pivot['Date']=="1/1/2015")]
# There are two values for water system

            PWSID  Water.System.Name Water.System.Classification  Year    Month      Date  Days.In.Month CALCULATED GPCD (Total Potable Produced in gallons per capita day)  Population Of Service Area  FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM  Non-Potable Produced Water (EXCLUDING RECYCLING)  RECYCLED WATER PRODUCED  TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)  TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)  WATER PRODUCED FROM GROUNDWATER  WATER PRODUCED FROM SURFACE WATER  WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM
104420  CA3410022  OLYMPIA MOBILODGE      Community Water System  2015  January  1/1/2015             31                                              78.6                                        450.0                                                NaN                                                                    NaN                      NaN                                          1096000.0                                                                                       1096000.0                                                                                       1096000.0                                NaN                                        NaN
104442  CA3410022  OLYMPIA MOBILODGE          Large Water System  2015  January  1/1/2015             31                                              78.6                                        450.0                                                NaN                                                                    NaN                      NaN                                          1096000.0                                                                                       1096000.0                                                                                       1096000.0                                NaN                                        NaN

In [47]:
prod_pivot['Water.System.Classification'].value_counts()

Community Water System                                      74348
Transient Noncommunity Water System                         51707
Nontransient Noncommunity Water System                      41000
Large Water System                                          34938
Privately owned, PUC-regulated, for profit water company       42
Privately owned business (non-community)                       34
Local Government                                               33
Name: Water.System.Classification, dtype: int64

In [48]:
# count the number of unique water systems per PWSID/Date
ctWaterSystems = prod_pivot.groupby(['PWSID','Date']).agg({"Water.System.Classification": lambda x: x.nunique()}).reset_index()

In [49]:
# Which PWSID/Dates have multiple water system classifications?
multipleClassifications = ctWaterSystems[ctWaterSystems['Water.System.Classification']>1]
multipleClassifications['key'] = multipleClassifications[['Date','PWSID']].apply(lambda x: "{}___{}".format(x[0],x[1]),axis=1)
multipleClassifications

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

            PWSID       Date  Water.System.Classification                    key
104405  CA3410022   1/1/2015                            2   1/1/2015___CA3410022
104407  CA3410022  10/1/2015                            2  10/1/2015___CA3410022
104409  CA3410022  11/1/2015                            2  11/1/2015___CA3410022
104411  CA3410022  12/1/2015                            2  12/1/2015___CA3410022
104413  CA3410022   2/1/2015                            2   2/1/2015___CA3410022
104417  CA3410022   5/1/2015                            2   5/1/2015___CA3410022
104419  CA3410022   6/1/2015                            2   6/1/2015___CA3410022
104421  CA3410022   7/1/2015                            2   7/1/2015___CA3410022
104423  CA3410022   8/1/2015                            2   8/1/2015___CA3410022
104425  CA3410022   9/1/2015                            2   9/1/2015___CA3410022
182988  CA5101009   1/1/2014                            2   1/1/2014___CA5101009
182992  CA5101009  10/1/2014                            2  10/1/2014___CA5101009
182996  CA5101009  11/1/2014                            2  11/1/2014___CA5101009
183000  CA5101009  12/1/2014                            2  12/1/2014___CA5101009
183004  CA5101009   2/1/2014                            2   2/1/2014___CA5101009
183008  CA5101009   3/1/2014                            2   3/1/2014___CA5101009
183012  CA5101009   4/1/2014                            2   4/1/2014___CA5101009
183016  CA5101009   5/1/2014                            2   5/1/2014___CA5101009
183020  CA5101009   6/1/2014                            2   6/1/2014___CA5101009
183024  CA5101009   7/1/2014                            2   7/1/2014___CA5101009
183028  CA5101009   8/1/2014                            2   8/1/2014___CA5101009
183032  CA5101009   9/1/2014                            2   9/1/2014___CA5101009
185868  CA5301201   1/1/2016                            2   1/1/2016___CA5301201
185870  CA5301201  10/1/2016                            2  10/1/2016___CA5301201
185872  CA5301201  11/1/2016                            2  11/1/2016___CA5301201
185873  CA5301201  12/1/2016                            2  12/1/2016___CA5301201
185874  CA5301201   2/1/2016                            2   2/1/2016___CA5301201
185875  CA5301201   3/1/2016                            2   3/1/2016___CA5301201
185876  CA5301201   4/1/2016                            2   4/1/2016___CA5301201
185877  CA5301201   5/1/2016                            2   5/1/2016___CA5301201
185879  CA5301201   6/1/2016                            2   6/1/2016___CA5301201
185881  CA5301201   7/1/2016                            2   7/1/2016___CA5301201
185883  CA5301201   8/1/2016                            2   8/1/2016___CA5301201
185885  CA5301201   9/1/2016                            2   9/1/2016___CA5301201

In [50]:
# Change Water System Classification to NA when a PWSID/Date has multiple water system classifications
prod_pivot['key'] = prod_pivot[['Date','PWSID']].apply(lambda x: "{}___{}".format(x[0],x[1]),axis=1)
prod_pivot.loc[prod_pivot['key'].isin(multipleClassifications['key']),'Water.System.Classification'] = np.nan

In [51]:
# Drops duplicate rows that previously existed due to multiple water system classifications being associated with
# one PWSID/Date
print(prod_pivot.shape)
prod_pivot = prod_pivot.drop_duplicates()
print(prod_pivot.shape)

(202102, 18)
(202068, 18)

In [52]:
# the PWSID/Date is now the unique key
rowCounts = prod_pivot.groupby(['PWSID','Date']).count().reset_index()
rowCounts[rowCounts['Water.System.Name']>1][0:4]

          PWSID       Date  Water.System.Name  Water.System.Classification  Year  Month  Days.In.Month  CALCULATED GPCD (Total Potable Produced in gallons per capita day)  Population Of Service Area  FINSIHIED WATER PURCHASED OR RECEIVED FROM ANOTHER PUBLIC WATER SYSTEM  Non-Potable Produced Water (EXCLUDING RECYCLING)  RECYCLED WATER PRODUCED  TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)  TOTAL POTABLE WATER PRODUCED USING REVISED UNITS (Total Does not Include Sold, Non-potable and Recycled amounts)  WATER PRODUCED FROM GROUNDWATER  WATER PRODUCED FROM SURFACE WATER  WATER SOLD TO ANOTHER PUBLIC WATER SYSTEM  key
6648  CA0610002   1/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1    2
6652  CA0610002  10/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1    2
6656  CA0610002  11/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1    2
6660  CA0610002  12/1/2013                  2                            2     2      2              2                                                  2                                            2                                                  0                                                                      0                        0                                                  1                                                                                               1                                                                                               1                                  0                                          1    2

In [53]:
prod_pivot.to_csv("{}1_initial_eda___prod.csv".format(processed_data_path),index=False)
print(prod_pivot.shape)

(202068, 18)

In [54]:
################
# What is the unique key of deliv_pivot?
#################

In [55]:
# The PWSID/Date is the unique key
rowCounts = deliv_pivot.groupby(['PWSID','Date']).count().reset_index()
rowCounts[rowCounts['Water.System.Name']>1][0:4]

Empty DataFrame
Columns: [PWSID, Date, Water.System.Name, Water.System.Classification, Year, Month, Days.In.Month, CALCULATED GPCD (Total delivery to residential in gallons per capita day), Population Of Service Area, Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS), WATER DELIVERIES TO  Agricultural, WATER DELIVERIES TO  Commercial.Institutional, WATER DELIVERIES TO  Industrial, WATER DELIVERIES TO  Landscape.Irrigation, WATER DELIVERIES TO  Multi.family.Residential, WATER DELIVERIES TO  Other.PWS, WATER DELIVERIES TO  Other, WATER DELIVERIES Total.Delivered Residential IN REVISED UNITS (Total Does not include Landscape Irrigation, Agricultural or to other PWS)]
Index: []

In [56]:
deliv_pivot.to_csv("{}1_initial_eda___deliv.csv".format(processed_data_path),index=False)
print(deliv_pivot.shape)

(75722, 18)

In [57]:
############
# Sanity check - are values the same across deliv and prod files?
############

In [58]:
joined = prod_pivot[['PWSID','Date','TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)']].\
    merge(deliv_pivot[['PWSID','Date','Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)']],on=["PWSID","Date"])

In [59]:
print("Total PWSID/Dates in both prod and deliv: {}".format(joined.shape[0]))
print("Total PWSID/Date combinations that have same value for potable water and delivered water: {}".format(joined[joined['TOTAL POTABLE WATER IN GALLONS (Total Does not Include Sold, Non-potable and Recycled amounts)']==joined["Total. RESIDENTIAL Delivered.Gallons (Total Does not include Landscape Irrigation, Agricultural or to other PWS)"]].shape[0]))

Total PWSID/Dates in both prod and deliv: 74111
Total PWSID/Date combinations that have same value for potable water and delivered water: 20011